# Generated by Django 4.2.2 on 2023-07-25 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coupons',
            fields=[
                ('title', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('content', models.CharField(blank=True, max_length=1000)),
                ('photo', models.TextField(blank=True)),
                ('price', models.CharField(max_length=10)),
                ('market_name', models.CharField(max_length=30)),
                ('post_date', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Купоны',
                'verbose_name_plural': 'Купоны',
                'unique_together': {('title', 'content')},
            },
        ),
    ]
